--!native
--!optimize 2

--[[
	******************************************************************************
	* @file		  	: ...soundController.luau
	* @author	  	: kadirdein77
	* @date		  	: September 2026
	* @lastEdit		: September 14 2026 21:13
	* @brief	  	: A basic sound controller.
	* @version		: 0.0.0
	******************************************************************************
	* @attention
	*
	* Copyright © 2026 Dein Corporation.
	* All rights reserved.
	*
	* This software is licensed under terms that can be found in the LICENSE file
	* in the root directory of this software component.
	* If no LICENSE file comes with this software, it is provided AS-IS.
	*
	******************************************************************************
--]]

--// Lib Decleration
local libs = script.libs
return require(libs.soundController)
